"""Auto-fix engine: categorize bugs, fetch code from GitHub, generate fixes via LLM, create PRs."""
import json
import httpx
import base64
import structlog
from datetime import datetime
from app.config import get_settings
from app.services.llm import LLMService
from app.services.dynamodb import DynamoDBService
from app.services.notifier import NotifierService
from app.services.code_analyzer import CodeAnalyzer, AUTO_FIXABLE_CATEGORIES

logger = structlog.get_logger()


class AutoFixService:
    def __init__(self):
        self.llm = LLMService()
        self.db = DynamoDBService()
        self.notifier = NotifierService()
        self.analyzer = CodeAnalyzer()
        self.settings = get_settings()

    def analyze_and_fix(self, error_message: str, stack_trace: str = "") -> dict:
        category = self.analyzer.categorize_error(error_message, stack_trace)
        frames = self.analyzer.parse_stack_trace(stack_trace)
        result = {"error_message": error_message, "category": category, "stack_frames": frames,
                  "source_code": None, "llm_analysis": None, "fix_generated": False, "pr_created": False, "pr_url": None}

        if not frames:
            result["llm_analysis"] = self.llm.analyze_error(error_message, stack_trace)
            self._audit(result)
            return result

        top = frames[0]
        repo_path = self.analyzer.extract_repo_path(top["file"])
        source = self.analyzer.fetch_file_from_github(repo_path)
        if not source:
            result["llm_analysis"] = self.llm.analyze_error(error_message, stack_trace)
            self._audit(result)
            return result

        ctx = self.analyzer.get_code_context(source["content"], top["line"])
        result["source_code"] = {"file_path": repo_path, "error_line": top["line"],
                                  "snippet": ctx["code_snippet"], "github_url": source["url"]}

        llm_result = self._analyze_with_code(error_message, stack_trace, repo_path, source["content"], ctx, category)
        result["llm_analysis"] = llm_result

        if category["auto_fixable"] and llm_result.get("confidence", 0) >= 0.8 and llm_result.get("fixed_code"):
            result["fix_generated"] = True
            pr = self._create_pr(repo_path, source, llm_result, error_message, category)
            if pr:
                result["pr_created"] = True
                result["pr_url"] = pr.get("html_url")
                self.notifier.send_teams_alert({
                    "api_path": repo_path, "alert_type": "auto_fix_pr_created",
                    "timestamp": datetime.utcnow().isoformat(),
                    "extra": f"PR: {pr.get('html_url', 'N/A')}",
                })

        self._audit(result)
        return result

    def _analyze_with_code(self, error: str, stack: str, path: str, content: str, ctx: dict, cat: dict) -> dict:
        prompt = f"""Analyze this Node.js error and generate a fix.
ERROR: {error}
STACK: {stack}
CATEGORY: {cat['category']} (auto_fixable: {cat['auto_fixable']})
FILE: {path}
CODE (line {ctx['error_line']}):
```javascript
{ctx['code_snippet']}
```
FULL FILE:
```javascript
{content[:8000]}
```
Respond in JSON: {{"root_cause": "...", "explanation": "...", "confidence": 0.0, "fixed_code": "...complete file...", "changes_summary": "..."}}"""
        try:
            return json.loads(self.llm.invoke(prompt, max_tokens=4096))
        except json.JSONDecodeError:
            return {"root_cause": "Parse failed", "confidence": 0.0, "fixed_code": None}
        except Exception as e:
            return {"root_cause": str(e), "confidence": 0.0, "fixed_code": None}

    def _create_pr(self, path: str, source: dict, llm: dict, error: str, cat: dict) -> dict | None:
        if not self.settings.github_token or not self.settings.github_repo:
            return None
        repo = self.settings.github_repo
        headers = {"Authorization": f"Bearer {self.settings.github_token}", "Accept": "application/vnd.github.v3+json"}
        base_url = f"https://api.github.com/repos/{repo}"
        branch = f"synapse-ops/auto-fix/{cat['category']}-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"

        try:
            with httpx.Client(timeout=20) as client:
                ref_resp = client.get(f"{base_url}/git/ref/heads/main", headers=headers)
                ref_resp.raise_for_status()
                sha = ref_resp.json()["object"]["sha"]
                branch_resp = client.post(f"{base_url}/git/refs", headers=headers, json={"ref": f"refs/heads/{branch}", "sha": sha})
                branch_resp.raise_for_status()
                file_resp = client.put(f"{base_url}/contents/{path}", headers=headers, json={
                    "message": f"fix({cat['category']}): {llm.get('changes_summary', 'auto-fix')}\n\nError: {error[:200]}\nGenerated by SynapseOps",
                    "content": base64.b64encode(llm["fixed_code"].encode()).decode(),
                    "sha": source["sha"], "branch": branch,
                })
                file_resp.raise_for_status()
                pr = client.post(f"{base_url}/pulls", headers=headers, json={
                    "title": f"[SynapseOps] fix({cat['category']}): {llm.get('changes_summary', 'auto-fix')[:80]}",
                    "body": f"## Auto-Fix\n**Error:** `{error[:300]}`\n**Category:** `{cat['category']}`\n**Confidence:** `{llm.get('confidence', 0)}`\n\n### Root Cause\n{llm.get('root_cause', 'N/A')}\n\n### Changes\n{llm.get('changes_summary', 'N/A')}",
                    "head": branch, "base": "main",
                }).json()
                logger.info("pr_created", url=pr.get("html_url"))
                return pr
        except Exception as e:
            logger.error("pr_creation_failed", error=str(e))
            return None

    def _audit(self, result: dict) -> None:
        self.db.store_audit_log({
            "action": "auto_fix_analysis", "error_message": result.get("error_message", ""),
            "category": result.get("category", {}).get("category", "unknown"),
            "fix_generated": result.get("fix_generated", False), "pr_created": result.get("pr_created", False),
            "pr_url": result.get("pr_url"), "timestamp": datetime.utcnow().isoformat(),
        })

    def get_fix_history(self, limit: int = 20) -> list[dict]:
        return self.db.get_audit_logs(action="auto_fix_analysis", limit=limit)
